<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistESLintLinter' => 'linter/ArcanistESLintLinter.php',
    'ArcanistFlowLinter' => 'linter/ArcanistFlowLinter.php',
    'JestTestEngine' => 'unit/engine/JestTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistESLintLinter' => 'ArcanistExternalLinter',
    'ArcanistFlowLinter' => 'ArcanistLinter',
    'JestTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
